import React, { createContext, useContext, useState } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'hero.title': 'Find local jobs — no login required',
    'hero.subtitle': 'Browse openings in Hindi, Kannada & English. Apply via voice or upload.',
    'nav.employers': 'Employers',
    'nav.admin': 'Admin Login',
    'jobs.browse': 'Browse Jobs',
    'jobs.search': 'Search jobs...',
    'jobs.location': 'Location',
    'jobs.apply': 'Apply Now',
    'jobs.save': 'Save Job',
    'apply.voice': 'Apply with Voice',
    'apply.upload': 'Upload Resume',
    'employer.post': 'Post a Job',
    'employer.login': 'Login',
    'footer.about': 'About',
    'footer.help': 'Help',
    'footer.contact': 'Contact',
    // JobsPage translations
    'jobs.title': 'Find Your Dream Job',
    'jobs.subtitle': 'Discover opportunities from top companies',
    'jobs.searchPlaceholder': 'Job title, keywords, or company',
    'jobs.locationPlaceholder': 'Location (e.g., Bangalore)',
    'jobs.found': 'Jobs Found',
    'jobs.noJobsFound': 'No jobs found',
    'jobs.noJobsDesc': 'Try adjusting your search criteria or filters',
    'jobs.clearFilters': 'Clear All Filters',
    'jobs.backToHome': 'Back to Home',
    'jobs.filters': 'Filters',
    'jobs.sort.latest': 'Latest Jobs',
    'jobs.sort.relevant': 'Most Relevant',
    'jobs.sort.salaryHigh': 'Highest Salary',
    'jobs.sort.salaryLow': 'Lowest Salary',
    'jobs.viewMode.grid': 'Grid View',
    'jobs.viewMode.list': 'List View',
    'jobs.quickApply': 'Quick Apply',
    'jobs.view': 'View',
    'jobs.viewDetails': 'View Details',
    'jobs.saveJob': 'Save Job',
    'jobs.saved': 'Saved',
    'jobs.applyNow': 'Apply Now',
    'jobs.close': 'Close',
    'jobs.jobId': 'Job ID',
    'jobs.postedTime': 'Posted',
    'jobs.fullTime': 'Full Time',
    'jobs.partTime': 'Part Time',
    'jobs.contract': 'Contract',
    'jobs.remote': 'Remote',
    'jobs.hybrid': 'Hybrid',
    'jobs.onSite': 'On-site',
    'jobs.experienceLevel.entry': 'Entry Level (0-2 years)',
    'jobs.experienceLevel.mid': 'Mid Level (2-5 years)',
    'jobs.experienceLevel.senior': 'Senior Level (5+ years)',
    'jobs.salaryRange': 'Salary Range',
    'jobs.jobDescription': 'Job Description',
    'jobs.requirements': 'Requirements',
    'jobs.skills': 'Required Skills',
    'jobs.benefits': 'Benefits & Perks',
    'jobs.aboutCompany': 'About',
    'jobs.companyProfile': 'Company Profile',
    'jobs.activeJobs': 'Active Jobs',
    'jobs.companies': 'Companies',
    'jobs.successRate': 'Success Rate',
    'jobs.thisWeek': 'This Week',
    'jobs.browseCategory': 'Browse by Category',
    'jobs.featuredJobs': 'Featured Jobs',
    'jobs.viewAll': 'View All',
    'jobs.salaryInsights': 'Salary Insights',
    'jobs.averageSalary': 'Average Salary',
    'jobs.topPaying': 'Top Paying',
    'jobs.entryLevel': 'Entry Level',
    'jobs.acrossPositions': 'Across all positions',
    'jobs.seniorTechRoles': 'Senior tech roles',
    'jobs.freshGraduates': 'Fresh graduates',
    'jobs.topHiringCompanies': 'Top Hiring Companies',
    'jobs.openPositions': 'open positions',
    'jobs.viewAllCompanies': 'View All Companies',
    'jobs.jobSearchTips': 'Job Search Tips',
    'jobs.quickActions': 'Quick Actions',
    'jobs.useVoiceApps': 'Use Voice Applications',
    'jobs.voiceAppDesc': 'Apply faster using our voice recording feature - no resume needed!',
    'jobs.filterBySalary': 'Filter by Salary Range',
    'jobs.filterSalaryDesc': 'Use our salary filters to find jobs matching your expectations.',
    'jobs.saveInteresting': 'Save Interesting Jobs',
    'jobs.saveJobDesc': 'Click the heart icon to save jobs and apply later.',
    'jobs.highestPaying': 'Highest Paying Jobs',
    'jobs.viewSalarySorted': 'View jobs sorted by salary',
    'jobs.latestJobs': 'Latest Jobs',
    'jobs.freshPostings': 'Fresh job postings from today',
    'jobs.entryLevelJobs': 'Entry Level Jobs',
    'jobs.perfectForGraduates': 'Perfect for fresh graduates',
    // HomePage specific translations
    'home.aiPowered': 'AI-Powered Job Platform',
    'home.yourVoice': 'Your Voice.',
    'home.yourCareer': 'Your Career.',
    'home.subtitle': 'Find your dream job with voice applications, multi-language support, and AI-powered resume matching.',
    'home.description': 'Udyoga Setu makes job applications simple and inclusive. Apply by uploading a resume or just speaking about your skills – in English, हिंदी, or ಕನ್ನಡ.',
    'search.jobTitle': 'Search jobs by role (e.g., Software Engineer, Data Analyst)',
    'search.location': 'Search by city or remote',
    'search.button': 'Search Jobs',
    'search.popular': 'Popular:',
    'home.browseJobs': 'Browse Jobs',
    'home.watchDemo': 'Watch Demo',
    // How It Works Section
    'home.howItWorks': 'How It Works',
    'home.howItWorksSubtitle': 'Simple, accessible job application process designed for everyone',
    'home.step1.title': 'Browse Jobs',
    'home.step1.description': 'Find opportunities in your preferred language without any registration required.',
    'home.step2.title': 'Apply with Voice',
    'home.step2.description': 'Record your responses in your local language - we\'ll create a resume for you.',
    'home.step3.title': 'Upload Resume',
    'home.step3.description': 'Already have a resume? Upload it directly or scan QR code at nearby kiosks.',
    'home.step4.title': 'Get Notified',
    'home.step4.description': 'Receive SMS updates on your application status and interview schedules.',
    // Offline Kiosks
    'home.offlineKiosks': 'Offline Kiosks Available',
    'home.offlineDescription': 'Can\'t access online? Visit one of our community kiosks in rural areas. Get help from trained operators and apply for jobs even without a smartphone.',
    'home.kiosksActive': 'Kiosks Active',
    'home.uptime': 'Uptime',
    'home.communitySupport': 'Community Support',
    'home.localAssistance': 'Local assistance available',
    'home.active247': '24/7 Active',
    // Stats
    'home.stats.activeJobs': 'Active Jobs',
    'home.stats.verifiedCompanies': 'Verified Companies',
    'home.stats.jobSeekers': 'Job Seekers',
    'home.stats.successRate': 'Success Rate',
    // Revolutionary Experience
    'home.revolutionary': 'Revolutionary Job Matching Experience',
    'home.revolutionarySubtitle': 'Experience the future of job applications with our AI-powered voice technology and seamless multi-language support.',
    'home.voiceFirst': 'Voice-First Applications',
    'home.voiceFirstDesc': 'Apply to jobs by simply speaking about your skills and experience.',
    'home.aiMatching': 'AI-Powered Matching',
    'home.aiMatchingDesc': 'Our AI analyzes your profile and matches you with perfect opportunities.',
    'home.multiLanguage': 'Multi-Language Support',
    'home.multiLanguageDesc': 'Communicate in your preferred language - English, Hindi, or Kannada.',
    'home.instantApply': 'Instant Apply',
    'home.voiceQr': 'Voice & QR',
    'home.languages': '3 Languages',
    // Commitment Section
    'home.commitment': 'We\'re committed to creating a safe, accessible platform for everyone',
    'home.verifiedEmployers': 'Verified Employers',
    'home.verifiedEmployersDesc': 'All companies are verified before posting jobs.',
    'home.verified': 'Verified',
    'home.communitySupportTitle': 'Community Support',
    'home.communitySupportDesc': 'Local operators help with applications.',
    'home.support247': '24/7 Support',
    'home.localPresence': 'Local Presence',
    'home.localPresenceDesc': 'Kiosks in rural areas across Karnataka.',
    'home.locations': 'Locations',
    'home.successStoriesTitle': 'Success Stories',
    'home.successStoriesDesc': 'Thousands of successful job placements.',
    'home.hired': 'Hired',
    // Success Stories Section
    'home.successStoriesHeading': 'Success Stories from Our Community',
    'home.successStoriesSubheading': 'Real people, real success - hear from job seekers who found their dream careers through our platform',
    'home.anitaQuote': '"मंने कभी नहीं सोचा था कि मैं सिर्फ बोलकर नौकरी पा सकूंगी। आज मैं एक शिक्षक हूँ!"',
    'home.rajeshQuote': '"ನಾನು ಕೀ ಸ್ಕಿಲ್ದ ಬೆಂ ದೊರೆಯಾದಾಗಾ ಕೆಲಸ ಮಾಡಲು ಆಯಸು ಆಚೆ। ಈಗ ನಾನು ಎಂಜಿನಿಯರ್!"',
    'home.mohammedQuote': '"The voice application feature helped me apply even though I don\'t have a resume."',
    // Company Registration
    'company.register.title': 'Company Registration',
    'company.register.subtitle': 'Create your company account to start posting jobs',
    'company.register.alreadySignedIn': 'You\'re already signed in!',
    'company.register.redirecting': 'Redirecting to your dashboard...',
    'company.register.goToDashboard': 'Go to Dashboard',
    // Company Login
    'company.login.alreadySignedIn': 'Welcome back!',
    'company.login.redirecting': 'You\'re already signed in. Access your dashboard.',
    'company.login.goToDashboard': 'Go to Dashboard',
    // Navigation
    'nav.companySignup': 'Company Signup',
    'nav.companyLogin': 'Company Login',
    'nav.dashboard': 'Dashboard',
    'nav.skill': 'Skill',
  },
  hi: {
    'hero.title': 'स्थानीय नौकरियां खोजें — पंजीकरण की आवश्यकता नहीं',
    'hero.subtitle': 'हिंदी, कन्नड़ और अंग्रेजी में अवसरों को ब्राउज़ करें। आवाज़ द्वारा या अपलोड करके आवेदन करें।',
    'nav.employers': 'नियोक्ता',
    'nav.admin': 'एडमिन लॉगिन',
    'jobs.browse': 'नौकरियां ब्राउज़ करें',
    'jobs.search': 'नौकरियां खोजें...',
    'jobs.location': 'स्थान',
    'jobs.apply': 'अभी आवेदन करें',
    'jobs.save': 'नौकरी सेव करें',
    'apply.voice': 'आवाज़ से आवेदन करें',
    'apply.upload': 'रिज्यूमे अपलोड करें',
    'employer.post': 'नौकरी पोस्ट करें',
    'employer.login': 'लॉगिन',
    'footer.about': 'के बारे में',
    'footer.help': 'सहायता',
    'footer.contact': 'संपर्क',
    // JobsPage translations
    'jobs.title': 'अपनी सपनों की नौकरी खोजें',
    'jobs.subtitle': 'शीर्ष कंपनियों के अवसरों की खोज करें',
    'jobs.searchPlaceholder': 'नौकरी का शीर्षक, खोजशब्द या कंपनी',
    'jobs.locationPlaceholder': 'स्थान (जैसे, बंगलौर)',
    'jobs.found': 'नौकरियां मिलीं',
    'jobs.noJobsFound': 'कोई नौकरी नहीं मिली',
    'jobs.noJobsDesc': 'अपने खोज मापदंड या फ़िल्टर को समायोजित करने का प्रयास करें',
    'jobs.clearFilters': 'सभी फ़िल्टर साफ़ करें',
    'jobs.backToHome': 'होम पर वापस',
    'jobs.filters': 'फ़िल्टर',
    'jobs.sort.latest': 'नवीनतम नौकरियां',
    'jobs.sort.relevant': 'सबसे प्रासंगिक',
    'jobs.sort.salaryHigh': 'उच्चतम वेतन',
    'jobs.sort.salaryLow': 'न्यूनतम वेतन',
    'jobs.viewMode.grid': 'ग्रिड व्यू',
    'jobs.viewMode.list': 'लिस्ट व्यू',
    'jobs.quickApply': 'तुरंत आवेदन करें',
    'jobs.view': 'देखें',
    'jobs.viewDetails': 'विवरण देखें',
    'jobs.saveJob': 'नौकरी सेव करें',
    'jobs.saved': 'सेव की गई',
    'jobs.applyNow': 'अभी आवेदन करें',
    'jobs.close': 'बंद करें',
    'jobs.jobId': 'नौकरी आईडी',
    'jobs.postedTime': 'पोस्ट किया गया',
    'jobs.fullTime': 'पूर्णकालिक',
    'jobs.partTime': 'अंशकालिक',
    'jobs.contract': 'अनुबंध',
    'jobs.remote': 'रिमोट',
    'jobs.hybrid': 'हाइब्रिड',
    'jobs.onSite': 'ऑन-साइट',
    'jobs.experienceLevel.entry': 'प्रवेश स्तर (0-2 वर्ष)',
    'jobs.experienceLevel.mid': 'मध्यम स्तर (2-5 वर्ष)',
    'jobs.experienceLevel.senior': 'वरिष्ठ स्तर (5+ वर्ष)',
    'jobs.salaryRange': 'वेतन सीमा',
    'jobs.jobDescription': 'नौकरी का विवरण',
    'jobs.requirements': 'आवश्यकताएं',
    'jobs.skills': 'आवश्यक कौशल',
    'jobs.benefits': 'लाभ और सुविधाएं',
    'jobs.aboutCompany': 'के बारे में',
    'jobs.companyProfile': 'कंपनी प्रोफ़ाइल',
    'jobs.activeJobs': 'सक्रिय नौकरियां',
    'jobs.companies': 'कंपनियां',
    'jobs.successRate': 'सफलता दर',
    'jobs.thisWeek': 'इस सप्ताह',
    'jobs.browseCategory': 'श्रेणी के अनुसार ब्राउज़ करें',
    'jobs.featuredJobs': 'फीचर्ड नौकरियां',
    'jobs.viewAll': 'सभी देखें',
    'jobs.salaryInsights': 'वेतन अंतर्दृष्टि',
    'jobs.averageSalary': 'औसत वेतन',
    'jobs.topPaying': 'शीर्ष भुगतान',
    'jobs.entryLevel': 'प्रवेश स्तर',
    'jobs.acrossPositions': 'सभी पदों में',
    'jobs.seniorTechRoles': 'वरिष्ठ तकनीकी भूमिकाएं',
    'jobs.freshGraduates': 'नए स्नातक',
    'jobs.topHiringCompanies': 'शीर्ष भर्ती कंपनियां',
    'jobs.openPositions': 'खुले पद',
    'jobs.viewAllCompanies': 'सभी कंपनियां देखें',
    'jobs.jobSearchTips': 'नौकरी खोज टिप्स',
    'jobs.quickActions': 'त्वरित कार्य',
    'jobs.useVoiceApps': 'आवाज़ आवेदन का उपयोग करें',
    'jobs.voiceAppDesc': 'हमारी आवाज़ रिकॉर्डिंग सुविधा का उपयोग करके तेज़ी से आवेदन करें - रिज्यूमे की आवश्यकता नहीं!',
    'jobs.filterBySalary': 'वेतन सीमा के अनुसार फ़िल्टर करें',
    'jobs.filterSalaryDesc': 'अपनी अपेक्षाओं के अनुरूप नौकरियां खोजने के लिए हमारे वेतन फ़िल्टर का उपयोग करें।',
    'jobs.saveInteresting': 'दिलचस्प नौकरियां सेव करें',
    'jobs.saveJobDesc': 'नौकरियों को सेव करने और बाद में आवेदन करने के लिए हृदय आइकन पर क्लिक करें।',
    'jobs.highestPaying': 'उच्चतम भुगतान वाली नौकरियां',
    'jobs.viewSalarySorted': 'वेतन के अनुसार क्रमबद्ध नौकरियां देखें',
    'jobs.latestJobs': 'नवीनतम नौकरियां',
    'jobs.freshPostings': 'आज की नई नौकरी पोस्टिंग',
    'jobs.entryLevelJobs': 'प्रवेश स्तर की नौकरियां',
    'jobs.perfectForGraduates': 'नए स्नातकों के लिए परफेक्ट',
    // Company Registration
    'company.register.title': 'कंपनी पंजीकरण',
    'company.register.subtitle': 'नौकरी पोस्ट करना शुरू करने के लिए अपना कंपनी खाता बनाएं',
    'company.register.alreadySignedIn': 'आप पहले से ही साइन इन हैं!',
    'company.register.redirecting': 'आपके डैशबोर्ड पर भेजा जा रहा है...',
    'company.register.goToDashboard': 'डैशबोर्ड पर जाएं',
    // Company Login
    'company.login.alreadySignedIn': 'आपका स्वागत है!',
    'company.login.redirecting': 'आप पहले से ही साइन इन हैं। अपने डैशबोर्ड तक पहुँचें।',
    'company.login.goToDashboard': 'डैशबोर्ड पर जाएं',
    // Navigation
    'nav.companySignup': 'कंपनी साइनअप',
    'nav.companyLogin': 'कंपनी लॉगिन',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.skill': 'कौशल',
    // HomePage specific translations
    'home.aiPowered': 'AI-संचालित नौकरी प्लेटफॉर्म',
    'home.yourVoice': 'आपकी आवाज़।',
    'home.yourCareer': 'आपका करियर।',
    'home.subtitle': 'आवाज़ आवेदन, बहु-भाषा समर्थन, और AI-संचालित रिज्यूमे मैचिंग के साथ अपनी सपनों की नौकरी पाएं।',
    'home.description': 'उद्योग सेतु नौकरी के आवेदन को सरल और समावेशी बनाता है। रिज्यूमे अपलोड करके या अपने कौशल के बारे में बोलकर आवेदन करें - अंग्रेजी, हिंदी, या ಕನ್ನಡ में।',
    'search.jobTitle': 'भूमिका के अनुसार नौकरी खोजें (जैसे, सॉफ्टवेयर इंजीनियर, डेटा विश्लेषक)',
    'search.location': 'शहर या रिमोट के अनुसार खोजें',
    'search.button': 'नौकरी खोजें',
    'search.popular': 'लोकप्रिय:',
    'home.browseJobs': 'नौकरियां ब्राउज़ करें',
    'home.watchDemo': 'डेमो देखें',
    // How It Works Section
    'home.howItWorks': 'यह कैसे काम करता है',
    'home.howItWorksSubtitle': 'सरल, सुलभ नौकरी आवेदन प्रक्रिया सभी के लिए डिज़ाइन की गई',
    'home.step1.title': 'नौकरियां ब्राउज़ करें',
    'home.step1.description': 'बिना किसी पंजीकरण की आवश्यकता के अपनी पसंदीदा भाषा में अवसर खोजें।',
    'home.step2.title': 'आवाज़ से आवेदन करें',
    'home.step2.description': 'अपनी स्थानीय भाषा में अपने उत्तर रिकॉर्ड करें - हम आपके लिए एक रिज्यूमे बनाएंगे।',
    'home.step3.title': 'रिज्यूमे अपलोड करें',
    'home.step3.description': 'पहले से ही रिज्यूमे है? इसे सीधे अपलोड करें या नज़दीकी कियोस्क पर QR कोड स्कैन करें।',
    'home.step4.title': 'सूचना प्राप्त करें',
    'home.step4.description': 'अपने आवेदन की स्थिति और इंटरव्यू शेड्यूल पर SMS अपडेट प्राप्त करें।',
    // Offline Kiosks
    'home.offlineKiosks': 'ऑफलाइन कियोस्क उपलब्ध',
    'home.offlineDescription': 'ऑनलाइन एक्सेस नहीं कर सकते? ग्रामीण क्षेत्रों में हमारे कम्युनिटी कियोस्क में से किसी एक पर जाएं। प्रशिक्षित ऑपरेटर से सहायता प्राप्त करें और स्मार्टफोन के बिना भी नौकरी के लिए आवेदन करें।',
    'home.kiosksActive': 'सक्रिय कियोस्क',
    'home.uptime': 'अपटाइम',
    'home.communitySupport': 'समुदायिक सहायता',
    'home.localAssistance': 'स्थानीय सहायता उपलब्ध',
    'home.active247': '24/7 सक्रिय',
    // Stats
    'home.stats.activeJobs': 'सक्रिय नौकरियां',
    'home.stats.verifiedCompanies': 'सत्यापित कंपनियां',
    'home.stats.jobSeekers': 'नौकरी खोजने वाले',
    'home.stats.successRate': 'सफलता दर',
    // Revolutionary Experience
    'home.revolutionary': 'क्रांतिकारी नौकरी मैचिंग अनुभव',
    'home.revolutionarySubtitle': 'हमारी AI-संचालित आवाज़ तकनीक और सहज बहु-भाषा समर्थन के साथ नौकरी आवेदन के भविष्य का अनुभव करें।',
    'home.voiceFirst': 'आवाज़-प्राथमिक आवेदन',
    'home.voiceFirstDesc': 'बस अपने कौशल और अनुभव के बारे में बोलकर नौकरी के लिए आवेदन करें।',
    'home.aiMatching': 'AI-संचालित मैचिंग',
    'home.aiMatchingDesc': 'हमारा AI आपकी प्रोफाइल का विश्लेषण करता है और आपको सही अवसरों से मैच करता है।',
    'home.multiLanguage': 'बहु-भाषा समर्थन',
    'home.multiLanguageDesc': 'अपनी पसंदीदा भाषा में संवाद करें - अंग्रेजी, हिंदी, या कन्नड़।',
    'home.instantApply': 'तुरंत आवेदन करें',
    'home.voiceQr': 'आवाज़ और QR',
    'home.languages': '3 भाषाएं',
    // Commitment Section
    'home.commitment': 'हम सभी के लिए एक सुरक्षित, सुलभ प्लेटफॉर्म बनाने के लिए प्रतिबद्ध हैं',
    'home.verifiedEmployers': 'सत्यापित नियोक्ता',
    'home.verifiedEmployersDesc': 'नौकरी पोस्ट करने से पहले सभी कंपनियां सत्यापित होती हैं।',
    'home.verified': 'सत्यापित',
    'home.communitySupportTitle': 'समुदायिक सहायता',
    'home.communitySupportDesc': 'स्थानीय ऑपरेटर आवेदन में सहायता करते हैं।',
    'home.support247': '24/7 सहायता',
    'home.localPresence': 'स्थानीय उपस्थिति',
    'home.localPresenceDesc': 'कर्नाटक के ग्रामीण क्षेत्रों में कियोस्क।',
    'home.locations': 'स्थान',
    'home.successStoriesTitle': 'सफलता की कहानियां',
    'home.successStoriesDesc': 'हजारों सफल नौकरी प्लेसमेंट।',
    'home.hired': 'नियुक्त',
    // Success Stories Section
    'home.successStoriesHeading': 'हमारे समुदाय की सफलता की कहानियां',
    'home.successStoriesSubheading': 'वास्तविक लोग, वास्तविक सफलता - उन नौकरी खोजने वालों से सुनें जिन्होंने हमारे प्लेटफॉर्म के माध्यम से अपने सपनों के करियर पाए',
    'home.anitaQuote': '"मंने कभी नहीं सोचा था कि मैं सिर्फ बोलकर नौकरी पा सकूंगी। आज मैं एक शिक्षक हूँ!"',
    'home.rajeshQuote': '"ನಾನು ಕೀ ಸ್ಕಿಲ್ದ ಬೆಂ ದೊರೆಯಾದಾಗಾ ಕೆಲಸ ಮಾಡಲು ಆಯಸು ಆಚೆ। ಈಗ ನಾನು ಎಂಜಿನಿಯರ್!"',
    'home.mohammedQuote': '"आवाज़ आवेदन सुविधा ने मुझे आवेदन करने में मदद की भले ही मेरे पास रिज्यूमे नहीं था।"',
  },
  kn: {
    'hero.title': 'ಸ್ಥಳೀಯ ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಿ — ನೋಂದಣಿ ಅಗತ್ಯವಿಲ್ಲ',
    'hero.subtitle': 'ಹಿಂದಿ, ಕನ್ನಡ ಮತ್ತು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಅವಕಾಶಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ। ಧ್ವನಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮೂಲಕ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ।',
    'nav.employers': 'ಉದ್ಯೋಗದಾತರು',
    'nav.admin': 'ಆಡಳಿತ ಲಾಗಿನ್',
    'jobs.browse': 'ಉದ್ಯೋಗಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    'jobs.search': 'ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಿ...',
    'jobs.location': 'ಸ್ಥಳ',
    'jobs.apply': 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'jobs.save': 'ಉದ್ಯೋಗ ಉಳಿಸಿ',
    'apply.voice': 'ಧ್ವನಿಯೊಂದಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'apply.upload': 'ರೆಸ್ಯೂಮ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'employer.post': 'ಉದ್ಯೋಗ ಪೋಸ್ಟ್ ಮಾಡಿ',
    'employer.login': 'ಲಾಗಿನ್',
    'footer.about': 'ಬಗ್ಗೆ',
    'footer.help': 'ಸಹಾಯ',
    'footer.contact': 'ಸಂಪರ್ಕ',
    // JobsPage translations
    'jobs.title': 'ನಿಮ್ಮ ಕನಸಿನ ಉದ್ಯೋಗವನ್ನು ಹುಡುಕಿ',
    'jobs.subtitle': 'ಉನ್ನತ ಕಂಪನಿಗಳ ಅವಕಾಶಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    'jobs.searchPlaceholder': 'ಉದ್ಯೋಗ ಶೀರ್ಷಿಕೆ, ಕೀವರ್ಡ್‌ಗಳು, ಅಥವಾ ಕಂಪನಿ',
    'jobs.locationPlaceholder': 'ಸ್ಥಳ (ಉದಾಹರಣೆ, ಬೆಂಗಳೂರು)',
    'jobs.found': 'ಉದ್ಯೋಗಗಳು ಕಂಡುಬಂದಿವೆ',
    'jobs.noJobsFound': 'ಯಾವುದೇ ಉದ್ಯೋಗ ಸಿಗಲಿಲ್ಲ',
    'jobs.noJobsDesc': 'ನಿಮ್ಮ ಹುಡುಕಾಟ ಮಾಪದಂಡಗಳು ಅಥವಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಸರಿಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ',
    'jobs.clearFilters': 'ಎಲ್ಲಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',
    'jobs.backToHome': 'ಮುಖ್ಯಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    'jobs.filters': 'ಫಿಲ್ಟರ್‌ಗಳು',
    'jobs.sort.latest': 'ಇತ್ತೀಚಿನ ಉದ್ಯೋಗಗಳು',
    'jobs.sort.relevant': 'ಅತ್ಯಂತ ಸಂಬಂಧಿತ',
    'jobs.sort.salaryHigh': 'ಅತ್ಯಧಿಕ ಸಂಬಳ',
    'jobs.sort.salaryLow': 'ಕನಿಷ್ಠ ಸಂಬಳ',
    'jobs.viewMode.grid': 'ಗ್ರಿಡ್ ವ್ಯೂ',
    'jobs.viewMode.list': 'ಲಿಸ್ಟ್ ವ್ಯೂ',
    'jobs.quickApply': 'ತ್ವರಿತ ಅರ್ಜಿ',
    'jobs.view': 'ನೋಡಿ',
    'jobs.viewDetails': 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    'jobs.saveJob': 'ಉದ್ಯೋಗ ಉಳಿಸಿ',
    'jobs.saved': 'ಉಳಿಸಲಾಗಿದೆ',
    'jobs.applyNow': 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'jobs.close': 'ಮುಚ್ಚಿ',
    'jobs.jobId': 'ಉದ್ಯೋಗ ಐಡಿ',
    'jobs.postedTime': 'ಪೋಸ್ಟ್ ಮಾಡಲಾಗಿದೆ',
    'jobs.fullTime': 'ಪೂರ್ಣಾವಧಿ',
    'jobs.partTime': 'ಅರ್ಧಾವಧಿ',
    'jobs.contract': 'ಒಪ್ಪಂದ',
    'jobs.remote': 'ರಿಮೋಟ್',
    'jobs.hybrid': 'ಹೈಬ್ರಿಡ್',
    'jobs.onSite': 'ಆನ್-ಸೈಟ್',
    'jobs.experienceLevel.entry': 'ಪ್ರವೇಶ ಹಂತ (0-2 ವರ್ಷಗಳು)',
    'jobs.experienceLevel.mid': 'ಮಧ್ಯಮ ಹಂತ (2-5 ವರ್ಷಗಳು)',
    'jobs.experienceLevel.senior': 'ಹಿರಿಯ ಹಂತ (5+ ವರ್ಷಗಳು)',
    'jobs.salaryRange': 'ಸಂಬಳ ವ್ಯಾಪ್ತಿ',
    'jobs.jobDescription': 'ಉದ್ಯೋಗ ವಿವರಣೆ',
    'jobs.requirements': 'ಅವಶ್ಯಕತೆಗಳು',
    'jobs.skills': 'ಅಗತ್ಯವಿರುವ ಕೌಶಲ್ಯಗಳು',
    'jobs.benefits': 'ಪ್ರಯೋಜನಗಳು ಮತ್ತು ಸೌಲಭ್ಯಗಳು',
    'jobs.aboutCompany': 'ಬಗ್ಗೆ',
    'jobs.companyProfile': 'ಕಂಪನಿ ಪ್ರೊಫೈಲ್',
    'jobs.activeJobs': 'ಸಕ್ರಿಯ ಉದ್ಯೋಗಗಳು',
    'jobs.companies': 'ಕಂಪನಿಗಳು',
    'jobs.successRate': 'ಯಶಸ್ಸಿನ ದರ',
    'jobs.thisWeek': 'ಈ ವಾರ',
    'jobs.browseCategory': 'ವರ್ಗದ ಪ್ರಕಾರ ಬ್ರೌಸ್ ಮಾಡಿ',
    'jobs.featuredJobs': 'ವೈಶಿಷ್ಟ್ಯಗೊಳಿಸಿದ ಉದ್ಯೋಗಗಳು',
    'jobs.viewAll': 'ಎಲ್ಲವನ್ನು ನೋಡಿ',
    'jobs.salaryInsights': 'ಸಂಬಳ ಒಳನೋಟಗಳು',
    'jobs.averageSalary': 'ಸರಾಸರಿ ಸಂಬಳ',
    'jobs.topPaying': 'ಅತ್ಯಧಿಕ ಪಾವತಿ',
    'jobs.entryLevel': 'ಪ್ರವೇಶ ಹಂತ',
    'jobs.acrossPositions': 'ಎಲ್ಲಾ ಸ್ಥಾನಗಳಲ್ಲಿ',
    'jobs.seniorTechRoles': 'ಹಿರಿಯ ತಾಂತ್ರಿಕ ಪಾತ್ರಗಳು',
    'jobs.freshGraduates': 'ಹೊಸ ಪದವೀಧರರು',
    'jobs.topHiringCompanies': 'ಉನ್ನತ ನೇಮಕಾತಿ ಕಂಪನಿಗಳು',
    'jobs.openPositions': 'ತೆರೆದ ಸ್ಥಾನಗಳು',
    'jobs.viewAllCompanies': 'ಎಲ್ಲಾ ಕಂಪನಿಗಳನ್ನು ನೋಡಿ',
    'jobs.jobSearchTips': 'ಉದ್ಯೋಗ ಹುಡುಕಾಟ ಸಲಹೆಗಳು',
    'jobs.quickActions': 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    'jobs.useVoiceApps': 'ಧ್ವನಿ ಅಪ್ಲಿಕೇಶನ್‌ಗಳನ್ನು ಬಳಸಿ',
    'jobs.voiceAppDesc': 'ನಮ್ಮ ಧ್ವನಿ ರೆಕಾರ್ಡಿಂಗ್ ಸೌಲಭ್ಯವನ್ನು ಬಳಸಿಕೊಂಡು ವೇಗವಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ - ರೆಸ್ಯೂಮ್ ಅಗತ್ಯವಿಲ್ಲ!',
    'jobs.filterBySalary': 'ಸಂಬಳ ವ್ಯಾಪ್ತಿಯ ಪ್ರಕಾರ ಫಿಲ್ಟರ್ ಮಾಡಿ',
    'jobs.filterSalaryDesc': 'ನಿಮ್ಮ ನಿರೀಕ್ಷೆಗಳಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಲು ನಮ್ಮ ಸಂಬಳ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಬಳಸಿ।',
    'jobs.saveInteresting': 'ಆಸಕ್ತಿದಾಯಕ ಉದ್ಯೋಗಗಳನ್ನು ಉಳಿಸಿ',
    'jobs.saveJobDesc': 'ಉದ್ಯೋಗಗಳನ್ನು ಉಳಿಸಲು ಮತ್ತು ನಂತರ ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಹೃದಯ ಐಕಾನ್ ಕ್ಲಿಕ್ ಮಾಡಿ।',
    'jobs.highestPaying': 'ಅತ್ಯಧಿಕ ಪಾವತಿಯ ಉದ್ಯೋಗಗಳು',
    'jobs.viewSalarySorted': 'ಸಂಬಳದ ಪ್ರಕಾರ ವರ್ಗೀಕರಿಸಿದ ಉದ್ಯೋಗಗಳನ್ನು ನೋಡಿ',
    'jobs.latestJobs': 'ಇತ್ತೀಚಿನ ಉದ್ಯೋಗಗಳು',
    'jobs.freshPostings': 'ಇಂದಿನ ಹೊಸ ಉದ್ಯೋಗ ಪೋಸ್ಟಿಂಗ್‌ಗಳು',
    'jobs.entryLevelJobs': 'ಪ್ರವೇಶ ಹಂತದ ಉದ್ಯೋಗಗಳು',
    'jobs.perfectForGraduates': 'ಹೊಸ ಪದವೀಧರರಿಗೆ ಪರಿಪೂರ್ಣ',
    // Company Registration
    'company.register.title': 'ಕಂಪನಿ ನೋಂದಣಿ',
    'company.register.subtitle': 'ಕಂಪನಿ ಖಾತೆಯನ್ನು ಸ್ರೆಷ್ಟಿಸಿ ಮತ್ತು ಉದ್ಯೋಗ ಪೋಸ್ಟ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ',
    'company.register.alreadySignedIn': 'ನೀವು ಈಗಾಗಲೇ ಸೈನ್ ಇನ್ ಆಗಿದ್ದೀರಿ!',
    'company.register.redirecting': 'ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ರಿಡೈರೆಕ್ಟ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'company.register.goToDashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ',
    // Company Login
    'company.login.alreadySignedIn': 'ವಾಪಸ್ ಸ್ವಾಗತ!',
    'company.login.redirecting': 'ನೀವು ಈಗಾಗಲೇ ಸೈನ್ ಇನ್ ಆಗಿದ್ದೀರಿ। ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನ್ನು ಪ್ರವೇಶಿಸಿ।',
    'company.login.goToDashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ',
    // Navigation
    'nav.companySignup': 'ಕಂಪನಿ ಸೈನ್ಅಪ್',
    'nav.companyLogin': 'ಕಂಪನಿ ಲಾಗಿನ್',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.skill': 'ಕೌಶಲ್ಯ',
    // HomePage specific translations
    'home.aiPowered': 'AI-ಚಾಲಿತ ಉದ್ಯೋಗ ಪ್ಲೇಟ್ಸೋರ್ಮ್',
    'home.yourVoice': 'ನಿಮ್ಮ ಕೂಗ.',
    'home.yourCareer': 'ನಿಮ್ಮ ಕರಿಯರ್.',
    'home.subtitle': 'ಕೂಗ ಅರ್ಜಿಗಳು, ಬಹು-ಭಾಷಾ ಸಹಾಯ ಮತ್ತು AI-ಚಾಲಿತ ರೆಸ೒ಮೆ ಮ೅ಚಿಂಗ್ ಸಹಿತ ನಿಮ್ಮ ಕನಸಿನ ಉದ್ಯೋಗವನ್ನು ಸಾಧಿಸಿ.',
    'home.description': 'ಉದ್ಯೋಗ ಸೇತು ಉದ್ಯೋಗ ಅರ್ಜಿಗಳನ್ನು ಸರಳ ಮತ್ತು ಸಮಾವೇಶಕವಾಗಿ ಮಾಡುತ್ತದೆ. ರೆಸ೒ಮೆ ಅಪ್ಲೋಡ್ ಮಾಡಲು ಅಥವಾ ನಿಮ್ಮ ಕೌಶಲ್ಯಗಳ ಬಗ್ಗೆ ಮಾತನಾಡಲು ಅರ್ಜಿ ಸಲ್ಲಿಸಿ - ಇಂಗ್ಲಿಷ್, हिंदी, ಅಥವಾ ಕನ್ನಡದಲ್ಲಿ.',
    'search.jobTitle': 'ಭೂಮಿಕೆಯ ಅನುಸಾರ ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಿ (ಉದಾಹರಣೆಗೆ, ಸಾಫ್ಟ್ವೆಯರ್ ಇಂಜಿನಿಯರ್, ಡೇಟಾ ವಿಶ್ಲೇಷಕ)',
    'search.location': 'ಶಹರ ಅಥವಾ ರಿಮೋಟ್ ಅನುಸಾರ ಹುಡುಕಿ',
    'search.button': 'ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಿ',
    'search.popular': 'ಲೋಕಪ್ರಿಯ:',
    'home.browseJobs': 'ಉದ್ಯೋಗಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    'home.watchDemo': 'ಡೆಮೋ ನೋಡಿ',
    // How It Works Section
    'home.howItWorks': 'ಇದು ಹೆಂಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    'home.howItWorksSubtitle': 'ಎಲ್ಲರಿಗೌ ಸರಳ, ಸುಲಭ ಉದ್ಯೋಗ ಅರ್ಜಿ ಪ್ರಕ್ರಿಯೆ',
    'home.step1.title': 'ಉದ್ಯೋಗಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    'home.step1.description': 'ಯಾವುದೇ ನೋಂದಣಿ ಆವಶ್ಯಕತೆ ಇಲ್ಲದೇ ನಿಮ್ಮ ಇಷ್ಟದ ಭಾಷೆಯಲ್ಲಿ ಅವಕಾಶಗಳನ್ನು ಹುಡುಕಿ.',
    'home.step2.title': 'ಕೂಗದಿಂದ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'home.step2.description': 'ನಿಮ್ಮ ಸ್ಥಾನೀಯ ಭಾಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಉತ್ತರಗಳನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ - ನಸಂಯ ರೆಸ೒ಮೆ ತಯಾರಿಸುತ್ತೇವೆ.',
    'home.step3.title': 'ರೆಸ೒ಮೆ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    'home.step3.description': 'ಮುಂದೇ ರೆಸ೒ಮೆ ಇದೆಯಾ? ಅದನ್ನು ನೇರವಾಗಿ ಅಪ್ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ಅಂತಿಕದ ಕಿಯಾಸ್ಕ್‌ಗಳಲ್ಲಿ QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ.',
    'home.step4.title': 'ಅಧಿಸೂಚನೆ ಸಿಗಲಿ',
    'home.step4.description': 'ನಿಮ್ಮ ಅರ್ಜಿಯ ಸ್ಥಿತಿ ಮತ್ತು ಇಂಟರ್ವಿಯೂ ಶೆಡ್ಯೂಲ್‌ಗಳ ಬಗ್ಗೆ SMS ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ಸ್ವೀಕರಿಸಿ.',
    // Offline Kiosks
    'home.offlineKiosks': 'ಆಫ್‌ಲೈನ್ ಕಿಯಾಸ್ಕ್‌ಗಳು ಉಪಲಬ್ಧ',
    'home.offlineDescription': 'ಆನ್‌ಲೈನ್ ಅಕ್ಸೆಸ್ ಮಾಡಲು ಆಗಲ್ಲೆ? ಗ್ರಾಮೀಣ ಪ್ರದೇಶಗಳಲ್ಲಿ ನಮ್ಮ ಸಮುದಾಯ ಕಿಯಾಸ್ಕ್‌ಗಳಲ್ಲಿ ಯಾವುದರಿಂದ ಿಸಿತ ಮಾಡಿ. ಪ್ರಶಿಕ್ಷಿತ ಆಪರೇಟರ್‌ಗಳಿಂದ ಸಹಾಯ ಸಿಗಿ ಮತ್ತು ಸ್ಮಾರ್ಟ್‌ಫೋನ್ ಇಲ್ಲದೇ ಉದ್ಯೋಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
    'home.kiosksActive': 'ಸಕ್ರಿಯ ಕಿಯಾಸ್ಕ್‌ಗಳು',
    'home.uptime': 'ಅಪ್‌ಟೈಮ್',
    'home.communitySupport': 'ಸಮುದಾಯಿಕ ಸಹಾಯ',
    'home.localAssistance': 'ಸ್ಥಾನೀಯ ಸಹಾಯ ಉಪಲಬ್ಧ',
    'home.active247': '24/7 ಸಕ್ರಿಯ',
    // Stats
    'home.stats.activeJobs': 'ಸಕ್ರಿಯ ಉದ್ಯೋಗಗಳು',
    'home.stats.verifiedCompanies': 'ಸತ್ಯಾಪಿತ ಕಂಪನಿಗಳು',
    'home.stats.jobSeekers': 'ಉದ್ಯೋಗ ಹುಡುಕುವವರು',
    'home.stats.successRate': 'ಸಫಲತೆ ದರ',
    // Revolutionary Experience
    'home.revolutionary': 'ಕ್ರಾಂತಿಕಾರಿ ಉದ್ಯೋಗ ಮ೅ಚಿಂಗ್ ಅನುಭವ',
    'home.revolutionarySubtitle': 'ನಮ್ಮ AI-ಚಾಲಿತ ಕೂಗ ತಂತ್ರಜ್ಞಾನ ಮತ್ತು ಅಭಿವೃದ್ಧಿಯೌತರ ಬಹು-ಭಾಷಾ ಸಹಾಯದಿಂದ ಉದ್ಯೋಗ ಅರ್ಜಿಗಳ ಭವಿಷ್ಯದ ಅನುಭವಿಸಿ.',
    'home.voiceFirst': 'ಕೂಗ-ಪ್ರಮುಖ ಅರ್ಜಿಗಳು',
    'home.voiceFirstDesc': 'ಸಕ್ಕತ ನಿಮ್ಮ ಕೌಶಲ್ಯ ಮತ್ತು ಅನುಭವದ ಬಗ್ಗೆ ಮಾತನಾಡುವ ಮೂಲಕ ಉದ್ಯೋಗಗಳಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
    'home.aiMatching': 'AI-ಚಾಲಿತ ಮ೅ಚಿಂಗ್',
    'home.aiMatchingDesc': 'ನಮ್ಮ AI ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ ಮತ್ತು ನಿಮ್ಮನ್ನು ಸರಿಯಾದ ಅವಕಾಶಗಳಿಂದ ಮ೅ಚ್ ಮಾಡುತ್ತದೆ.',
    'home.multiLanguage': 'ಬಹು-ಭಾಷಾ ಸಹಾಯ',
    'home.multiLanguageDesc': 'ನಿಮ್ಮ ಇಷ್ಟದ ಭಾಷೆಯಲ್ಲಿ ಸಂವಾದ ನಡೆಸಿ - ಇಂಗ್ಲಿಷ್, हिंदी, ಅಥವಾ ಕನ್ನಡ.',
    'home.instantApply': 'ತುರನ್ತ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'home.voiceQr': 'ಕೂಗ & QR',
    'home.languages': '3 ಭಾಷೆಗಳು',
    // Commitment Section
    'home.commitment': 'ನಾವು ಎಲ್ಲರಿಗೌ ಸುರಕ್ಷಿತ, ಸುಲಭ ಪ್ಲೇಟ್‌ಫಾರ್ಮ್ ನಿರ್ಮಿಸಲು ಪ್ರತಿಬದ್ಧರಾಗಿದ್ದೇವೆ',
    'home.verifiedEmployers': 'ಸತ್ಯಾಪಿತ ನಿಯೋಜಕರು',
    'home.verifiedEmployersDesc': 'ಉದ್ಯೋಗ ಪೋಸ್ಟ್ ಮಾಡುವ ಮುಂದೆ ಎಲ್ಲಾ ಕಂಪನಿಗಳು ಸತ್ಯಾಪಿತವಾಗಿವೆ.',
    'home.verified': 'ಸತ್ಯಾಪಿತ',
    'home.communitySupportTitle': 'ಸಮುದಾಯಿಕ ಸಹಾಯ',
    'home.communitySupportDesc': 'ಸ್ಥಾನೀಯ ಆಪರೇಟರ್‌ಗಳು ಅರ್ಜಿಗಳಲ್ಲಿ ಸಹಾಯ ಮಾಡುತ್ತಾರೆ.',
    'home.support247': '24/7 ಸಹಾಯ',
    'home.localPresence': 'ಸ್ಥಾನೀಯ ಉಪಸ್ಥಿತಿ',
    'home.localPresenceDesc': 'ಕರ್ನಾಟಕದ ಗ್ರಾಮೀಣ ಪ್ರದೇಶಗಳಲ್ಲಿ ಕಿಯಾಸ್ಕ್‌ಗಳು.',
    'home.locations': 'ಸ್ಥಳಗಳು',
    'home.successStoriesTitle': 'ಸಫಲತೆಯ ಕಥೆಗಳು',
    'home.successStoriesDesc': 'ಸಾವಿರರು ಸಫಲ ಉದ್ಯೋಗ ನಿಯೋಜನೆಗಳು.',
    'home.hired': 'ನಿಯೋಜನೆ',
    // Success Stories Section
    'home.successStoriesHeading': 'ನಮ್ಮ ಸಮುದಾಯದ ಸಫಲತೆಯ ಕಥೆಗಳು',
    'home.successStoriesSubheading': 'ಸ್ವರೂಪದ ಜನರು, ಸರಿಯಾದ ಸಫಲತೆ - ನಮ್ಮ ಪ್ಲೇಟ್‌ಫಾರ್ಮ್ ಅತಾವೆಕ ತಮ್ಮ ಕನಸಿನ ಕರಿಯರ್‌ಗಳನ್ನು ಹುಡುಕಿದ ಉದ್ಯೋಗ ಅರ್ಥಿಕರ ಜೋಡಿಗೆ ಕೇಳಿ',
    'home.anitaQuote': '"मंने कभी नहीं सोचा था कि मैं सिर्फ बोलकर नौकरी पा सकूंगी। आज मैं एक शिक्षक हूँ!"',
    'home.rajeshQuote': '"ನಾನು ಕೀ ಸ್ಕಿಲ್ದ ಬೆಂ ದೊರೆಯಾದಾಗಾ ಕೆಲಸ ಮಾಡಲು ಆಯಸು ಆಚೆ। ಈಗ ನಾನು ಎಂಜಿನಿಯರ್!"',
    'home.mohammedQuote': '"ಕೂಗ ಅರ್ಜಿ ಸುವಿಧೆಯು ನನಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಸಹಾಯ ಮಾಡಿದು ನನಗೆ ರೆಸ೒ಮೆ ಇರಲಿಲ್ಲದರೂ."',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string, fallback?: string): string => {
    const translation = translations[language]?.[key as keyof typeof translations.en];
    if (translation) return translation;
    
    // Fallback to English if current language doesn't have the key
    const englishTranslation = translations.en[key as keyof typeof translations.en];
    if (englishTranslation) return englishTranslation;
    
    // Use provided fallback or return the key itself
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};